# Aggregating DataFrames 

En este notebook, se calcularan estadisticas en columnas del DataFrame y dominaras las estadisticas agrupadas y tablas dinamicas  (pivot table)

## Estadistucas de Resumen

**Media y Mediana**

Las estadisticas resumidas son exactamente lo que parecen: resumen muchos numeros en una sola estadistica. Por ejemplo, la media, la mediana, el minimo, y la desviacion tipica(Desviacion estandar) son estadisticas de resumen. Calcular estadisticas de resumen te permite hacerte una mejor idea de tus datos, aunque sean muchos.

**Instrucciones**

- Explorar el nuevo DataFrame imprimiendo las primeras filas del DataFrame walmart_sales

- Imprimir informacion sobre las columnas

- Imprimir la media de la columna weekly_sales

- Imprimir la mediana de la columna weekly_sales

In [61]:
import pandas as pd

In [62]:
sales = pd.read_csv('./Datasets/walmart_sales.csv')
sales.head()

,Store,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment
0,1,05-02-2010,1643690.90,0,42.31,2.572,211.096358,8.106
1,1,12-02-2010,1641957.44,1,38.51,2.548,211.242170,8.106
2,1,19-02-2010,1611968.17,0,39.93,2.514,211.289143,8.106
3,1,26-02-2010,1409727.59,0,46.63,2.561,211.319643,8.106
4,1,05-03-2010,1554806.68,0,46.50,2.625,211.350143,8.106

In [63]:
sales.shape # Tama;o del DATAFRAME

(6435, 8)

In [64]:
sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6435 entries, 0 to 6434
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Store         6435 non-null   int64
 1   Date          6435 non-null   object
 2   Weekly_Sales  6435 non-null   float64
 3   Holiday_Flag  6435 non-null   int64
 4   Temperature   6435 non-null   float64
 5   Fuel_Price    6435 non-null   float64
 6   CPI           6435 non-null   float64
 7   Unemployment  6435 non-null   float64
dtypes: float64(5), int64(2), object(1)
memory usage: 402.3+ KB

In [65]:
sales.describe()

,Store,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment
count,6435.000000,6.435000e+03,6435.000000,6435.000000,6435.000000,6435.000000,6435.000000
mean,23.000000,1.046965e+06,0.069930,60.663782,3.358607,171.578394,7.999151
std,12.988182,5.643666e+05,0.255049,18.444933,0.459020,39.356712,1.875885
min,1.000000,2.099862e+05,0.000000,-2.060000,2.472000,126.064000,3.879000
25%,12.000000,5.533501e+05,0.000000,47.460000,2.933000,131.735000,6.891000
50%,23.000000,9.607460e+05,0.000000,62.670000,3.445000,182.616521,7.874000
75%,34.000000,1.420159e+06,0.000000,74.940000,3.735000,212.743293,8.622000
max,45.000000,3.818686e+06,1.000000,100.140000,4.468000,227.232807,14.313000

In [66]:
# Media de la columna weekly_sales
sales['Weekly_Sales'].mean()

np.float64(1046964.8775617715)

In [67]:
# Media de la columna weekly_sales
round(sales['Weekly_Sales'].mean(), 2)

np.float64(1046964.88)

In [68]:
# Media de la columna weekly_sales
sales['Weekly_Sales'].median()

np.float64(960746.04)

## Resumir Fechas

Las Estadisticas sumarias tambien pueden calcularse sibre columnas de fecha que tengan valores con el tipo de dato datetime64. Algunas estadisticas de resumen como la media no tienen mucho sentido en las fechas, pero otras son extremadamente utilies como, por ejemplo, el minimo y el maximo, que te permiten ver que el intervalo de tiempo abarcan tus datos.

**Instrucciones**

- Imprimir el maximo de la columna date
- Imprimir el minimo de la columna date

In [69]:
sales["Date"].astype("datetime64[ns]")

0      2010-05-02
1      2010-12-02
2      2010-02-19
3      2010-02-26
4      2010-05-03
          ...
6430   2012-09-28
6431   2012-05-10
6432   2012-12-10
6433   2012-10-19
6434   2012-10-26
Name: Date, Length: 6435, dtype: datetime64[ns]

In [70]:
sales['Date'].max()

'31-12-2010'

In [71]:
sales['Date'].min()

'01-04-2011'

## Funcion agg

Aunque pandas y numpy tienen muchas funciones, a veces puedes necesitar una funcion diferente para resumir los datos.

El metodo .agg() Permite aplicar tus propias funciones personalizadas a un DataFrame, asi como aplicar funciones a mas de una columna de un DataFrame a la vez, haciendo que tus agregaciones sean muy eficientes.

`df['column'].agg(function)`

En  la funcion personalizada para este ejercicio de 'IQR' es la abreviatura del rango intercuartilico, que es el percentil 75 menos el percentil 25. Es una alternativa a la desviacion tipica (estandar) que resulta util si tus datos contienen valores atipicos.

**Instrucciones**

1. Utiliza la funcion personalizada IQR definida por ti junto con el metodo .agg() para imprimir la IQR de la columna temperature_c de sales.

1. Actualiza la seleccion de columnas para utilizar la funcion personalizada iqr con agg() para imprimir los IQR de las columnas temperature, fuel_price_usd, unemployment, en orden. 
1. Actualiza las llamadas a la funcion agg, para obtener el IQR y la mediana en ese orden

In [72]:
import numpy as np

In [73]:
# Funcion Personalizada que calcula el IQR

def iqr(column):
    return column.quantile(0.75) - column.quantile(0.25)

# Imprimir el IQR de la columna Temperature
print(sales['Temperature'].quantile(0.75))
print(sales['Temperature'].quantile(0.25))

print(sales['Temperature'].agg(iqr))

print(sales['Temperature'].agg(['mean', 'median', 'max', 'min']))

74.94
47.46
27.479999999999997
mean       60.663782
median     62.670000
max       100.140000
min        -2.060000
Name: Temperature, dtype: float64

In [74]:
def iqr (columna):
    return columna.quantile(0.75) - columna.quantile(0.25)

In [75]:
# Imprimir IQR de la columna temperature

print (f'El IQR de Temperatura {sales['Temperature'].agg(iqr)}')

# Actualizar la impresion del IQR de temperature, Fuel_price, unemployment
print(sales[['Temperature', 'Fuel_Price', 'Unemployment']].agg(iqr))

El IQR de Temperatura 27.479999999999997
Temperature     27.480
Fuel_Price       0.802
Unemployment     1.731
dtype: float64

In [76]:
print(sales[['Temperature', 'Fuel_Price', 'Unemployment']].agg([iqr, np.median]))

        Temperature  Fuel_Price  Unemployment
iqr           27.48       0.802         1.731
median        62.67       3.445         7.874

C:\Users\luis2\AppData\Local\Temp\ipykernel_31624\1972042188.py:1: FutureWarning: The provided callable <function median at 0x000002D0C6C23EC0> is currently using Series.median. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "median" instead.
  print(sales[['Temperature', 'Fuel_Price', 'Unemployment']].agg([iqr, np.median]))
C:\Users\luis2\AppData\Local\Temp\ipykernel_31624\1972042188.py:1: FutureWarning: The provided callable <function median at 0x000002D0C6C23EC0> is currently using Series.median. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "median" instead.
  print(sales[['Temperature', 'Fuel_Price', 'Unemployment']].agg([iqr, np.median]))
C:\Users\luis2\AppData\Local\Temp\ipykernel_31624\1972042188.py:1: FutureWarning: The provided callable <function median at 0x000002D0C6C23EC0> is currently using Series.median. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "median" instead.
  print(sales[['Temperature', 'Fuel_Price', 'Unemployment']].agg([iqr, np.median]))

In [77]:
print(sales[['Temperature', 'Fuel_Price', 'Unemployment']].agg([iqr, 'median']))

        Temperature  Fuel_Price  Unemployment
iqr           27.48       0.802         1.731
median        62.67       3.445         7.874

In [78]:
print(sales[['Temperature', 'Fuel_Price', 'Unemployment']].agg([iqr, 'median', 'mean', 'max', 'min']))

        Temperature  Fuel_Price  Unemployment
iqr       27.480000    0.802000      1.731000
median    62.670000    3.445000      7.874000
mean      60.663782    3.358607      7.999151
max      100.140000    4.468000     14.313000
min       -2.060000    2.472000      3.879000

In [79]:
def convertirACentigrados (faren):
    return (faren - 32) / 1.8

In [80]:
temp_min = sales['Temperature'].min()
temp_max = sales['Temperature'].max()

In [81]:
print(f'La temperatura {temp_min} en centigrados {convertirACentigrados(temp_min)}')

La temperatura -2.06 en centigrados -18.922222222222224

In [82]:
print(f'La tempertura {temp_min} en Centigrados es {convertirACentigrados(temp_min)}')
print(f'La tempertura {temp_max} en Centigrados es {convertirACentigrados(temp_max)}')

La tempertura -2.06 en Centigrados es -18.922222222222224
La tempertura 100.14 en Centigrados es 37.855555555555554

In [83]:
print(sales[['Temperature']].agg(convertirACentigrados))

      Temperature
0        5.727778
1        3.616667
2        4.405556
3        8.127778
4        8.055556
...           ...
6430    18.266667
6431    18.272222
6432    12.483333
6433    13.594444
6434    14.916667

[6435 rows x 1 columns]

In [84]:
sales['Temperature_Celsious'] = sales[['Temperature']].agg(convertirACentigrados)

In [85]:
sales_sort = sales.sort_values(['Temperature', 'Temperature_Celsious'], ascending=[True, True])

In [86]:
sales_sort[['Temperature', 'Temperature_Celsious']]

      Temperature  Temperature_Celsious
910         -2.06            -18.922222
3626         5.54            -14.700000
2336         6.23            -14.316667
959          7.46            -13.633333
5628         9.51            -12.494444
...           ...                   ...
3885        99.22             37.344444
5315        99.22             37.344444
4657        99.66             37.588889
4707       100.07             37.816667
4599       100.14             37.855556

[6435 rows x 2 columns]

## Estadisticas Acumuladas

Las estadísticas acumulativas también pueden ser útiles para hacer un seguimiento de las estadísticas resumidas a lo largo del tiempo. En este ejercicio, calcularás la suma acumulada y el máximo acumulado de las ventas semanales de un departamento, lo que te permitirá identificar cuáles han sido las ventas totales hasta el momento, así como cuáles han sido las ventas semanales más elevadas hasta el momento.

**Instrucciones**

- Ordena las filas de sales_1_1 por la columna date en orden ascendente.
- Obtén la suma acumulada de weekly_sales y añádelo como una nueva columna de sales_1_1 llamada cum_weekly_sales.
- Obtén el máximo acumulado de weekly_sales, y añádelo como una columna llamada cum_max_sales.
- Imprime las columnas date, weekly_sales, cum_weekly_sales, y cum_max_sales.

In [87]:
sales_1_1 = sales[sales['Store'] == 1]

# Ordenar sales_1_1 por fecha

sales_1_1 = sales_1_1.sort_values('Date')

# Obtner la suma acumulativa de Weekly_sales y agregar una columna llamada cum_weekly_sales

sales_1_1['cum_weekly_sales'] = sales_1_1['Weekly_Sales'].cumsum()

In [88]:
sales_1_1[['Weekly_Sales', 'cum_weekly_sales']]

     Weekly_Sales  cum_weekly_sales
60     1495064.75      1.495065e+06
121    1624477.58      3.119542e+06
73     1488538.09      4.608080e+06
34     1453329.50      6.061410e+06
108    1688420.76      7.749831e+06
..            ...               ...
25     1371986.60      2.165614e+08
86     1394561.83      2.179559e+08
99     1497462.72      2.194534e+08
134    1582083.40      2.210355e+08
47     1367320.01      2.224028e+08

[143 rows x 2 columns]

In [89]:
sales_1_1.head()

,Store,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment,Temperature_Celsious,cum_weekly_sales
60,1,01-04-2011,1495064.75,0,59.17,3.524,214.837166,7.682,15.094444,1495064.75
121,1,01-06-2012,1624477.58,0,77.95,3.501,221.747214,7.143,25.527778,3119542.33
73,1,01-07-2011,1488538.09,0,85.55,3.524,215.184137,7.962,29.750000,4608080.42
34,1,01-10-2010,1453329.50,0,71.89,2.603,211.671989,7.838,22.161111,6061409.92
108,1,02-03-2012,1688420.76,0,60.96,3.630,220.848045,7.348,16.088889,7749830.68

In [90]:
# Obtener el maximo acumulativo de weekly_sales y agregar una nueva columna llamada cum_max_sales

sales_1_1['cum_max_sales'] = sales_1_1['Weekly_Sales'].cummax()

sales_1_1.head()

,Store,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment,Temperature_Celsious,cum_weekly_sales,cum_max_sales
60,1,01-04-2011,1495064.75,0,59.17,3.524,214.837166,7.682,15.094444,1495064.75,1495064.75
121,1,01-06-2012,1624477.58,0,77.95,3.501,221.747214,7.143,25.527778,3119542.33,1624477.58
73,1,01-07-2011,1488538.09,0,85.55,3.524,215.184137,7.962,29.750000,4608080.42,1624477.58
34,1,01-10-2010,1453329.50,0,71.89,2.603,211.671989,7.838,22.161111,6061409.92,1624477.58
108,1,02-03-2012,1688420.76,0,60.96,3.630,220.848045,7.348,16.088889,7749830.68,1688420.76

In [91]:
# Mostrar las columnas calculadas
sales_1_1[['Date', 'Weekly_Sales', 'cum_weekly_sales', 'cum_max_sales']]

           Date  Weekly_Sales  cum_weekly_sales  cum_max_sales
60   01-04-2011    1495064.75      1.495065e+06     1495064.75
121  01-06-2012    1624477.58      3.119542e+06     1624477.58
73   01-07-2011    1488538.09      4.608080e+06     1624477.58
34   01-10-2010    1453329.50      6.061410e+06     1624477.58
108  02-03-2012    1688420.76      7.749831e+06     1688420.76
..          ...           ...               ...            ...
25   30-07-2010    1371986.60      2.165614e+08     2387950.20
86   30-09-2011    1394561.83      2.179559e+08     2387950.20
99   30-12-2011    1497462.72      2.194534e+08     2387950.20
134  31-08-2012    1582083.40      2.210355e+08     2387950.20
47   31-12-2010    1367320.01      2.224028e+08     2387950.20

[143 rows x 4 columns]

## Recuento

### Eliminar Duplicados

Eliminar duplicados es una habilidad esencial para obtener recuentos precisos, porque a menudo no quieres contar lo mismo varias veces. En este ejercicio, crearás algunos DataFrames nuevos utilizando valores únicos de sales.

**Instrucciones**

- Elimina las filas de sales con pares duplicados de store y type y guárdalas como store_types e imprime la cabecera.
- Elimina las filas de sales con pares duplicados de store y department y guárdalas como store_depts e imprime la cabecera.
- Subconjunta las filas que sean semanas de vacaciones utilizando la columna is_holiday, y elimina las dates duplicadas, guardándolas como holiday_dates.
- Selecciona la columna date de holiday_dates, e imprímela.

In [92]:
import pandas as pd

sales_sub = pd.read_csv('./Datasets/sales_subset.csv', index_col = 0)

In [93]:
sales_sub.head()

,store,type,department,date,weekly_sales,is_holiday,temperature_c,fuel_price_usd_per_l,unemployment
0,1,A,1,2010-02-05,24924.50,False,5.727778,0.679451,8.106
1,1,A,1,2010-03-05,21827.90,False,8.055556,0.693452,8.106
2,1,A,1,2010-04-02,57258.43,False,16.816667,0.718284,7.808
3,1,A,1,2010-05-07,17413.94,False,22.527778,0.748928,7.808
4,1,A,1,2010-06-04,17558.09,False,27.050000,0.714586,7.808

In [94]:
# Eliminar (drop) la combinacion de duplicados de store/type
store_types = sales_sub.drop_duplicates(subset=['store', 'type'])
store_types.head()

,store,type,department,date,weekly_sales,is_holiday,temperature_c,fuel_price_usd_per_l,unemployment
0,1,A,1,2010-02-05,24924.50,False,5.727778,0.679451,8.106
901,2,A,1,2010-02-05,35034.06,False,4.550000,0.679451,8.324
1798,4,A,1,2010-02-05,38724.42,False,6.533333,0.686319,8.623
2699,6,A,1,2010-02-05,25619.00,False,4.683333,0.679451,7.259
3593,10,B,1,2010-02-05,40212.84,False,12.411111,0.782478,9.765

In [95]:
# eliminar los duplicados de la combinacion de store y department

store_depts = sales_sub.drop_duplicates(subset=['store', 'department'])
store_depts.head()

,store,type,department,date,weekly_sales,is_holiday,temperature_c,fuel_price_usd_per_l,unemployment
0,1,A,1,2010-02-05,24924.50,False,5.727778,0.679451,8.106
12,1,A,2,2010-02-05,50605.27,False,5.727778,0.679451,8.106
24,1,A,3,2010-02-05,13740.12,False,5.727778,0.679451,8.106
36,1,A,4,2010-02-05,39954.04,False,5.727778,0.679451,8.106
48,1,A,5,2010-02-05,32229.38,False,5.727778,0.679451,8.106

In [96]:
# Segmentar las filas donde isholiday sea true y eliminar las fechas duplicadas de date y almacenarlas en holiday_dates
holiday_dates = sales_sub[sales_sub['is_holiday'] == True].drop_duplicates(subset='date')
holiday_dates['date']

498     2010-09-10
691     2011-11-25
2315    2010-02-12
6735    2012-09-07
6810    2010-12-31
6815    2012-02-10
6820    2011-09-09
Name: date, dtype: object

### Contar variables categóricas

Contar es una forma estupenda de tener una visión general de tus datos y de detectar curiosidades que de otro modo no notarías. En este ejercicio, contarás el número de cada tipo de tienda y el número de cada número de departamento utilizando los DataFrames que creaste en el ejercicio anterior:
```
# Drop duplicate store/type combinations
store_types = sales.drop_duplicates(subset=["store", "type"])

# Drop duplicate store/department combinations
store_depts = sales.drop_duplicates(subset=["store", "department"])

```
Los DataFrames store_types y store_depts que creaste en el último ejercicio están disponibles, y pandas se importa como pd.

**Instrucciones**

- Cuenta el número de tiendas de cada tienda type en store_types.
- Cuenta la proporción de tiendas de cada tienda type en store_types.
- Cuenta el número de tiendas de cada department en store_depts, ordenando los recuentos en orden descendente.
- Cuenta la proporción de tiendas de cada department en store_depts, ordenando las proporciones en orden descendente.

In [97]:
store_types.head()

,store,type,department,date,weekly_sales,is_holiday,temperature_c,fuel_price_usd_per_l,unemployment
0,1,A,1,2010-02-05,24924.50,False,5.727778,0.679451,8.106
901,2,A,1,2010-02-05,35034.06,False,4.550000,0.679451,8.324
1798,4,A,1,2010-02-05,38724.42,False,6.533333,0.686319,8.623
2699,6,A,1,2010-02-05,25619.00,False,4.683333,0.679451,7.259
3593,10,B,1,2010-02-05,40212.84,False,12.411111,0.782478,9.765

In [98]:
store_types[['type']]

     type
0       A
901     A
1798    A
2699    A
3593    B
4495    A
5408    A
6293    A
7199    A
8109    A
9009    A
9899    A

In [99]:
# Contar el numero de tienda de cada tipo 
store_counts = store_types['type'].value_counts()
store_counts

type
A    11
B     1
Name: count, dtype: int64

In [100]:
# Obtener la proporcion de tiendas de cada tipo
store_props = store_types['type'].value_counts(normalize=True) * 100
store_props

type
A    91.666667
B     8.333333
Name: proportion, dtype: float64

In [101]:
# Contar el numero de tiendas por cada departamento y ordenado 
dept_counts_sorted = store_depts['department'].value_counts(sort=True)
dept_counts_sorted

department
1     12
2     12
3     12
4     12
5     12
      ..
37    10
48     8
50     6
39     4
43     2
Name: count, Length: 80, dtype: int64

In [102]:
# Obtener la proporcion de las tiendas en cada departamento y ordenadas
store_props_sorted = store_depts['department'].value_counts(sort=True, normalize=True) * 100
store_props_sorted

department
1     1.291712
2     1.291712
3     1.291712
4     1.291712
5     1.291712
        ...
37    1.076426
48    0.861141
50    0.645856
39    0.430571
43    0.215285
Name: proportion, Length: 80, dtype: float64

### ¿Qué porcentaje de ventas se produjo en cada tipo de tienda?

Aunque .groupby() es útil, puedes calcular estadísticas de resumen agrupadas sin él.

Walmart distingue tres tipos de tiendas: "supercentros", "tiendas de descuento" y "mercados de barrio", codificados en este conjunto de datos como tipo "A", "B" y "C". En este ejercicio, calcularás las ventas totales realizadas en cada tipo de tienda, sin utilizar .groupby(). A continuación, puedes utilizar estas cifras para ver qué proporción de las ventas totales de Walmart se realizaron en cada tipo.

sales está disponible y pandas se importa como pd.

**Instrucciones**

- Calcula el total de weekly_sales en todo el conjunto de datos.
- Subconjunto para las tiendas type "A", y calcula sus ventas semanales totales.
- Haz lo mismo en las tiendas type "B" y type "C".
- Combina los resultados A/B/C en una lista, y divídela por sales_all para obtener la proporción de ventas por tipo.

In [103]:
# Calcular el total de ventas por semana 
sales_all = sales_sub['weekly_sales'].sum()
sales_all

np.float64(256894718.89999998)

In [104]:
# Segmentar para los tipo A, calcular el total de ventas por semana
sales_A = sales_sub[sales_sub['type'] == 'A']['weekly_sales'].sum()
sales_A

np.float64(233716315.01)

In [105]:
# Segmentar para los tipo B, calcular el total de ventas por semana
sales_B = sales_sub[sales_sub['type'] == 'B']['weekly_sales'].sum()
sales_B

np.float64(23178403.89)

In [106]:
# Segmentar para los tipo C, calcular el total de ventas por semana
sales_C = sales_sub[sales_sub['type'] == 'C']['weekly_sales'].sum()
sales_C

np.float64(0.0)

In [107]:
# Obtener la proporcion de cada tipo 
sales_props_by_type = [sales_A, sales_B, sales_C] / sales_all * 100
sales_props_by_type

array([90.97746969,  9.02253031,  0.        ])

### Cálculos con .groupby()

El método .groupby() te facilita mucho la vida. En este ejercicio, realizarás los mismos cálculos que la última vez, excepto que utilizarás el método .groupby(). También realizarás cálculos sobre datos agrupados por dos variables para ver si las ventas difieren por tipo de tienda dependiendo de si es una semana festiva o no.

sales está disponible y pandas se carga como pd.

**Instrucciones**

- Agrupa sales por "type", toma la suma de "weekly_sales", y almacénala como sales_by_type.
- Calcula la proporción de ventas en cada tipo de tienda dividiendo por la suma de sales_by_type. Asignar a sales_propn_by_type.
- Agrupa sales por "type" y "is_holiday", toma la suma de weekly_sales, y almacénala como sales_by_type_is_holiday.

In [108]:
# Agrupar por tipo; calcular el total de ventas semanales \
sales_by_type = sales_sub.groupby('type')['weekly_sales'].sum()
sales_by_type

type
A    2.337163e+08
B    2.317840e+07
Name: weekly_sales, dtype: float64

In [109]:
# Obtener la proporcion de cada tipo
sales_props_by_type = sales_by_type / sum(sales_by_type) * 100
sales_props_by_type

type
A    90.97747
B     9.02253
Name: weekly_sales, dtype: float64

In [110]:
# Agrupar por type y por is_holiday; y calcular el total de ventas ACHERON
sales_by_type_is_holiday = sales_sub.groupby(['type', 'is_holiday'])['weekly_sales'].sum()
sales_by_type_is_holiday

type  is_holiday
A     False         2.336927e+08
      True          2.360181e+04
B     False         2.317678e+07
      True          1.621410e+03
Name: weekly_sales, dtype: float64

### Múltiples resúmenes agrupados

Anteriormente en este capítulo, has visto que el método .agg() es útil para calcular múltiples estadísticos sobre múltiples variables. También funciona con datos agrupados. NumPy, que se importa como np, tiene muchas funciones estadísticas de resumen diferentes, entre las que se incluyen: np.min, np.max, np.mean, y np.median.

sales está disponible y pandas se importa como pd.

**Instrucciones**

- Importa numpy con el alias np.
- Obtén el mínimo, el máximo, la media y la mediana de weekly_sales para cada tipo de tienda utilizando .groupby() y .agg(). Guárdalo como . ¡Asegúrate de utilizar las funciones de numpy!
- Obtén el mínimo, el máximo, la media y la mediana de unemployment y fuel_price_usd_per_l para cada tipo de tienda. Guárdalo como unemp_fuel_stats.

In [111]:
# Para cada tipo de tienda, vamos hacer una agregacio para weekly_sales: obtener el min, max y la media
import numpy as np
sales_stats = sales_sub.groupby('type')['weekly_sales'].agg([np.min, np.max, np.median, np.mean])
sales_stats

C:\Users\luis2\AppData\Local\Temp\ipykernel_31624\621072431.py:3: FutureWarning: The provided callable <function min at 0x000002D0C6AB6AC0> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  sales_stats = sales_sub.groupby('type')['weekly_sales'].agg([np.min, np.max, np.median, np.mean])
C:\Users\luis2\AppData\Local\Temp\ipykernel_31624\621072431.py:3: FutureWarning: The provided callable <function max at 0x000002D0C6AB6980> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  sales_stats = sales_sub.groupby('type')['weekly_sales'].agg([np.min, np.max, np.median, np.mean])
C:\Users\luis2\AppData\Local\Temp\ipykernel_31624\621072431.py:3: FutureWarning: The provided callable <function median at 0x000002D0C6C23EC0> is currently using SeriesGroupBy.median. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "median" instead.
  sales_stats = sales_sub.groupby('type')['weekly_sales'].agg([np.min, np.max, np.median, np.mean])
C:\Users\luis2\AppData\Local\Temp\ipykernel_31624\621072431.py:3: FutureWarning: The provided callable <function mean at 0x000002D0C6AB7380> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  sales_stats = sales_sub.groupby('type')['weekly_sales'].agg([np.min, np.max, np.median, np.mean])

         min        max    median          mean
type
A    -1098.0  293966.05  11943.92  23674.667242
B     -798.0  232558.51  13336.08  25696.678370

In [112]:
# Para cada tipo de tienda, vamos hacer una agregacio para weekly_sales: obtener el min, max y la media
import numpy as np
sales_stats = sales_sub.groupby('type')['weekly_sales'].agg([ 'min', 'max', 'median', 'mean'])
sales_stats

         min        max    median          mean
type
A    -1098.0  293966.05  11943.92  23674.667242
B     -798.0  232558.51  13336.08  25696.678370

In [113]:
# Para cada tipo de tienda, vamos aplicar agregacion para los campos unemployment y fuel_price_usd_per_l: obtener min, max, mean y median
unemp_fuel_stats = sales_sub.groupby('type')[['unemployment', 'fuel_price_usd_per_l']].agg([ 'min', 'max', 'median', 'mean'])
unemp_fuel_stats

     unemployment                         fuel_price_usd_per_l            \
              min    max median      mean                  min       max
type
A           3.879  8.992  8.067  7.972611             0.664129  1.107410
B           7.170  9.765  9.199  9.279323             0.760023  1.107674


        median      mean
type
A     0.735455  0.744619
B     0.803348  0.805858

## Pivot tables (Tablas Dinamicas)

### Pivotar sobre una variable

Las tablas dinámicas son la forma estándar de agregar datos en las hojas de cálculo.

En pandas, las tablas dinámicas son esencialmente otra forma de realizar cálculos agrupados. Es decir, el método .pivot_table() es una alternativa a .groupby().

En este ejercicio, realizarás cálculos utilizando .pivot_table() para reproducir los cálculos que realizaste en la lección anterior utilizando .groupby().

sales está disponible y pandas se importa como pd.

**Instrucciones**

- Obtén la media weekly_sales mediante type utilizando .pivot_table() y almacénala como mean_sales_by_type.
- Obtén la media y la mediana (utilizando funciones NumPy) de weekly_sales por type utilizando .pivot_table() y almacénalas como mean_med_sales_by_type.
- Obtén la media de weekly_sales mediante type y is_holiday mediante .pivot_table() y guárdala como mean_sales_by_type_holiday.

In [114]:
sales = pd.read_csv('./Datasets/sales_subset.csv', index_col=0)

In [115]:
sales.head()

,store,type,department,date,weekly_sales,is_holiday,temperature_c,fuel_price_usd_per_l,unemployment
0,1,A,1,2010-02-05,24924.50,False,5.727778,0.679451,8.106
1,1,A,1,2010-03-05,21827.90,False,8.055556,0.693452,8.106
2,1,A,1,2010-04-02,57258.43,False,16.816667,0.718284,7.808
3,1,A,1,2010-05-07,17413.94,False,22.527778,0.748928,7.808
4,1,A,1,2010-06-04,17558.09,False,27.050000,0.714586,7.808

In [116]:
# pivot para la media para cada tipo de tienda 
mean_sales_by_type = sales.pivot_table(values='weekly_sales', index='type')
mean_sales_by_type

      weekly_sales
type
A     23674.667242
B     25696.678370

In [117]:
# pivot de la media y la mediana de weekly_sales por cada tipo de tienda
mean_med_sales_by_type = sales.pivot_table(values= 'weekly_sales', index='type', aggfunc=['mean', 'median'])
mean_med_sales_by_type

              mean       median
      weekly_sales weekly_sales
type
A     23674.667242     11943.92
B     25696.678370     13336.08

In [118]:
# pivot para la media de weekly_sales por tipo de tienda y holiday

mean_sales_by_type_holiday = sales.pivot_table(values='weekly_sales', index='type', columns='is_holiday')
mean_sales_by_type_holiday

is_holiday         False      True
type
A           23768.583523  590.04525
B           25751.980533  810.70500

In [119]:
# pivot para la media de weekly_sales por tipo de tienda y holiday

mean_sales_by_type_holiday = sales.pivot_table(values='weekly_sales', index='type', columns='is_holiday', aggfunc=['mean', 'median','std'])
mean_sales_by_type_holiday

                    mean                median                    std  \
is_holiday         False      True       False    True          False
type
A           23768.583523  590.04525  12028.955   37.500  30154.488578
B           25751.980533  810.70500  13348.680  810.705  31168.339501


is_holiday        True
type
A           1065.825755
B           1102.089558

## Rellena los valores que faltan y suma valores con tablas dinámicas

El método .pivot_table() tiene varios argumentos útiles, como fill_value y margins.

*fill_value* sustituye los valores que faltan por un valor real (lo que se conoce como imputación). Con qué sustituir los valores ausentes es un tema lo suficientemente amplio como para tener su propio curso(Cómo tratar los datos ausentes en Python), pero lo más sencillo es sustituirlos por un valor ficticio.

*margins* es un atajo para cuando pivotas por dos variables, pero también quieres pivotar por cada una de esas variables por separado: da los totales de fila y columna del contenido de la tabla pivotante.

En este ejercicio, practicarás el uso de estos argumentos para mejorar tus habilidades con las tablas dinámicas, ¡lo que te ayudará a hacer números de forma más eficiente!

sales está disponible y pandas se importa como pd.

*Instrucciones*

1. Imprime la media weekly_sales por department y type, completando los valores que falten con 0.
2. Imprime la media weekly_sales por department y type, completando los valores que falten con 0 y sumando todas las filas y columnas.

In [121]:
# 1. Imprime la media weekly_sales por department y type, completando los valores que falten con 0.
sales.pivot_table('weekly_sales', index='department', columns='type',fill_value=0)

type                    A              B
department
1            30961.725379   44050.626667
2            67600.158788  112958.526667
3            17160.002955   30580.655000
4            44285.399091   51219.654167
5            34821.011364   63236.875000
...                   ...            ...
95          123933.787121   77082.102500
96           21367.042857    9528.538333
97           28471.266970    5828.873333
98           12875.423182     217.428333
99             379.123659       0.000000

[80 rows x 2 columns]

In [122]:
# 2. Imprime la media weekly_sales por department y type, completando los valores que falten con 0 y sumando todas las filas y columnas.
sales.pivot_table('weekly_sales', index='department', columns='type', fill_value=0,margins=True)

type                   A              B           All
department
1           30961.725379   44050.626667  32052.467153
2           67600.158788  112958.526667  71380.022778
3           17160.002955   30580.655000  18278.390625
4           44285.399091   51219.654167  44863.253681
5           34821.011364   63236.875000  37189.000000
...                  ...            ...           ...
96          21367.042857    9528.538333  20337.607681
97          28471.266970    5828.873333  26584.400833
98          12875.423182     217.428333  11820.590278
99            379.123659       0.000000    379.123659
All         23674.667242   25696.678370  23843.950149

[81 rows x 3 columns]